### ISSUE TITLE
Appears to require missing config.ini file

### ISSUE THREAD

**Issue by dsjstc** [musashin/CSVToKML#1]
> Traceback (most recent call last):
>   File "./CSVToKML.py", line 127, in <module>
>     loadConfig(os.path.join(os.path.dirname(_CSV_Path), "config.ini"), row)
>   File "./CSVToKML.py", line 46, in loadConfig
>     start_time = config.getfloat('GENERAL', 'STARTTIME')
>   File "/usr/lib/python2.7/ConfigParser.py", line 362, in getfloat
>     return self._get(section, float, option)
>   File "/usr/lib/python2.7/ConfigParser.py", line 356, in _get
>     return conv(self.get(section, option))
>   File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
>     raise NoSectionError(section)
> ConfigParser.NoSectionError: No section: 'GENERAL'
>

**Comment by musashin** [comment]
Just committed a sample

**Comment by dsjstc** [comment]
Thanks!
